import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Vlad Romanov",
  "jobTitle": "Consultant, Automation & Manufacturing",
  "worksFor": {
    "@type": "Organization",
    "name": "Joltek"
  },
  "alumniOf": [
    { "@type": "CollegeOrUniversity", "name": "Concordia University" },
    { "@type": "CollegeOrUniversity", "name": "McGill University" }
  ],
  "hasOccupation": [
    {
      "@type": "Occupation",
      "name": "Manufacturing Consultant",
      "description": "Specializing in automation, SCADA/MES, and IT/OT strategy",
      "estimatedSalary": {
        "@type": "MonetaryAmount",
        "currency": "USD",
        "value": { "@type": "QuantitativeValue", "value": "150000", "unitText": "YEAR" }
      }
    }
  ],
  "knowsAbout": ["SCADA", "MES", "PLC", "Digital Transformation", "Factory Modernization"],
  "url": "https://www.vladromanov.com"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personSchema) }}
        />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
